# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-16 13:19
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Friendship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('added', models.DateField(default=datetime.date.today)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='_unused_', to=settings.AUTH_USER_MODEL)),
                ('to_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('tmdbID', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imdbID', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=700)),
                ('year', models.CharField(max_length=100)),
                ('rated', models.CharField(max_length=100)),
                ('released', models.CharField(max_length=100)),
                ('runtime', models.CharField(max_length=100)),
                ('genre', models.CharField(max_length=250)),
                ('director', models.CharField(max_length=400)),
                ('writer', models.CharField(max_length=400)),
                ('actors', models.CharField(max_length=600)),
                ('plot', models.TextField()),
                ('language', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('poster', models.CharField(max_length=1000)),
                ('metascore', models.CharField(max_length=50)),
                ('imdbRating', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('friends', models.ManyToManyField(blank=True, to='movieapp.Friendship')),
                ('toWatchList', models.ManyToManyField(blank=True, related_name='toWatch', to='movieapp.Movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('watchedList', models.ManyToManyField(blank=True, related_name='watched', to='movieapp.Movie')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='friendship',
            unique_together=set([('to_user', 'from_user')]),
        ),
    ]
