# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-19 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0004_auto_20160919_1245'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password',
            field=models.CharField(default='', max_length=20),
        ),
    ]
